### ISSUE TITLE
import `IoError` conflicts

### ISSUE THREAD

**Issue by wayhome** [erickt/rust-mustache#29]
Hello, I met the following errors when run `cargo build`:

   Compiling rust-mustache v0.3.0 (https://github.com/erickt/rust-mustache#50d41983)
/Users/youngking/.cargo/git/checkouts/rust-mustache-8a34535dd7ccd89d/master/src/encoder.rs:3:5: 3:21 error: import `IoError` conflicts with type in this module
/Users/youngking/.cargo/git/checkouts/rust-mustache-8a34535dd7ccd89d/master/src/encoder.rs:3 use std::io::IoError;
                                                                                                 ^~~~~~~~~~~~~~~~
/Users/youngking/.cargo/git/checkouts/rust-mustache-8a34535dd7ccd89d/master/src/encoder.rs:24:5: 24:21 note: conflicting type here
/Users/youngking/.cargo/git/checkouts/rust-mustache-8a34535dd7ccd89d/master/src/encoder.rs:24     IoError(IoError),
                                                                                                  ^~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `rust-mustache`.

And my rustc version is  rustc 0.12.0-nightly.

**Comment by erickt** [comment]
Ownership has moved to https://github.com/nickel-org/rust-mustache, but this has long been fixed!
