### ISSUE TITLE
Explain that this repo is unmaintained in README

### ISSUE THREAD

**Issue by SimonPersson** [erickt/rust-mustache#38]
Hi!

I noticed that this repo still shows up as the top google result for "Rust Mustache". Could you perhaps add a notice in the README that this is unmaintained and link to the fork by [nickel-org](https://github.com/nickel-org/rust-mustache), so that potential users can easily find it?

**Comment by LukasKalbertodt** [comment]
Yes please!

**Comment by erickt** [comment]
Ownership has been moved to nickel-org!
